### ISSUE TITLE
issue after adding tracking number

### ISSUE THREAD

**Issue by jap88** [fireshaper/parcelpony#1]
Really liking this, after i add a tracking number with the given carrier the next screen is just a blank screen point to index.php. is the correct behavior for this? below is a screen shot of the blank screen i get

![Screen Shot 2020-08-03 at 1 55 24 PM](https://user-images.githubusercontent.com/66313335/89212156-fde6f500-d590-11ea-91d9-9237b113e06a.png)

**Comment by fireshaper** [comment]
I just uploaded a new version a few minutes ago. Try with that one and see if you get the same error.

**Comment by jap88** [comment]
newest version seems to be missing carriers drop-down menu and the add button on the main homepage. im running php 7.3 not sure if that causes anything to mess up. i put a screenshot below of what im referring to

![image](https://user-images.githubusercontent.com/66313335/89216744-f62b4e80-d598-11ea-8969-b31797a6c80c.png)

**Comment by fireshaper** [comment]
Which browser are you using?

**Comment by jap88** [comment]
firefox

**Comment by fireshaper** [comment]
Does https://belowland.com/parcelpony show up correct for you? (disregard the PHP errors)

**Comment by jap88** [comment]
yes it does

**Comment by fireshaper** [comment]
It's got to be the PHP version then. I developed this on a server running 7.2.18. Let me do some testing and see what's going on.

**Comment by jap88** [comment]
sure thing, in the mean time let me try a lower php version. thanks alot!

**Comment by jap88** [comment]
update: tried with php 7.2 still seeing the same screen as mentioned before. going to do some of my own troubleshooting. let me know if you make any breakthroughs

**Comment by fireshaper** [comment]
Haven't been able to repro this. Have you found anything else on you end?

**Comment by jap88** [comment]
I have not, ive tried many different versions of ubuntu and also centos still with no luck. ive even tried MAC.....version 7.2 of php seems to cause the least amount of issues, the only issue i have is it not displaying the list of carriers in the drop down menu. see the screenshot for reference.

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/66313335/91172201-c78d2900-e6a9-11ea-976d-1e14989f4328.png">

**Comment by fireshaper** [comment]
@jap88 That problem happens when the page either can't make a connection to the trackinghive site, or you haven't filled in the bearerToken on the index.php page.

**Comment by fireshaper** [comment]
Closing this issue since there hasn't been any updates on it in a while.
